os:
- linux
- osx

language: generic
osx_image: xcode11.3
sudo: required
dist: buster

env:
- SWIFT_VERSION=5.2.4

install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
- swift test
